### ISSUE TITLE
select all button for a specific object

### ISSUE THREAD

**Issue by David280gg** [HJfod/BetterEdit#115]
just like the delete all button but select instead of delete, so for example you can make all the spikes noclip by selecting them all and making them notouch (bc passable doesnt work in spikes) and make a noclip level in 10 minutes just adding the portals. i cant remember how many times i wished this option existed

**Comment by Geming400** [comment]
You can already do that, go to any levels in the edit mode, press `ESCAPE` and select `select filter`. Once you have done that, select the object that you will want to "**select all**", go to the `delete` tab and press custom. And now you can select all of the objects you want:D

Here is a video:

https://github.com/HJfod/BetterEdit/assets/101340400/0b055f92-be92-4a99-9176-b3617f04fb78
