### ISSUE TITLE
Game-Version Editor Restrictions Idea

### ISSUE THREAD

**Issue by DShifter** [HJfod/BetterEdit#12]
Can you add custom editor tab-presets that restrict the objects and triggers available based on a sort of "version selector" interface that is pre-settable upon creating a new level, for people wanting to build strictly for older updates? With this, is it also possible to modify the editor height to the height it was in the selected version (for example, it's 100 in 2.1, 40 in 1.6, and 50 in 1.8), but leave the floor alone/keep it at 5/6 below the floor? Along with this, based on the version selected, can GD's first max obj count be changed from 40,000 in 2.1 to whatever it was in the selected version (30k in 2.0, 8k in 1.6, etc, but allow infinite objects after this cap is reached like normal)?

**Comment by HJfod** [comment]
Hi! This feature has been requested multiple times and I will be adding it to the BetterEdit rewrite happening for lilac :)

**Comment by DShifter** [comment]
> Hi! This feature has been requested multiple times and I will be adding it to the BetterEdit rewrite happening for lilac :)

Awesome! Looking forward to using it :D
