### ISSUE TITLE
Go back to first layer button crashes the game

### ISSUE THREAD

**Issue by JustLudwig** [HJfod/BetterEdit#120]
The cyan arrow that sends you to layer 0 crashes the game

Im on mobile 64 bit

**Please attach the latest crash report from `<GD folder>/geode/crashlogs`**
[2024-02-03_23-04-55.log](https://github.com/HJfod/BetterEdit/files/14230771/2024-02-03_23-04-55.log)

**Comment by CattoDev** [comment]
Can't seem to reproduce the bug, try updating your geode loader (you seem to be using beta 13?)
