### ISSUE TITLE
AI Decoration

### ISSUE THREAD

**Issue by TurtleLegend64** [HJfod/BetterEdit#129]
I Saw it on the tweet and it looked cool. but can you release it to the public in the next update? that would be cool and easy.
Link of old tweet: https://twitter.com/HJfod/status/1642131626086871040

**Comment by Fnige** [comment]
You realise that this was an april fools post right? lol

**Comment by TurtleLegend64** [comment]
> You realise that this was an april fools post right? lol

**why do i exitst. just to suffer**

**Comment by HJfod** [comment]
I will never add anything AI-related to BE.
