### ISSUE TITLE
Hard crash when pressing the show scale controls hotkey

### ISSUE THREAD

**Issue by ghost** [HJfod/BetterEdit#145]
**How to replicate:**
1. Assign a key or key combination to Show Scale Control
2. Place and select any object
3. Press the assigned key

[2024-02-11_17-05-43.log](https://github.com/HJfod/BetterEdit/files/14232822/2024-02-11_17-05-43.log)

All mods unrelated to the process were disabled beforehand (except Node IDs)
Windows 11 Home 21H2

![Screenshot_20240211_170450](https://github.com/HJfod/BetterEdit/assets/144915512/29253535-3f70-4836-873c-3bf8e5be3527)

**Comment by HJfod** [comment]
Fixed in next update, coming in a few hours
