### ISSUE TITLE
Object link

### ISSUE THREAD

**Issue by blaze264** [HJfod/BetterEdit#151]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/2cec62bc-d984-4557-981f-759a88606d83">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa">
    <img alt="GitHub Octicons: Beaker" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa" margin="0px">
  </picture>
  Suggestion
  <br />
</h1>
Suggest a new feature to be added.
<hr />

### How should it work?
It will have a button that links objects into 1 object 

### What does it look/sound/act like?
It will look like a chain link button near the zoom buttons

### What is its purpose?
To link objects together

**Comment by Alphalaneous** [comment]
That's a vanilla GD feature, just enable it in the editor settings
