### ISSUE TITLE
editor layer visibility in playtest mode

### ISSUE THREAD

**Issue by TheGarbageMann** [HJfod/BetterEdit#154]
it's just the "all" in the editor layer selector being visible while playtesting

https://github.com/HJfod/BetterEdit/assets/92222030/7d94a56f-f2a8-4e8d-a50b-2d15ed7b8569

famous words of penguinz0/moist cr1tikal, "That's about it, see ya"

**Comment by HJfod** [comment]
This has been fixed in next release!
