### ISSUE TITLE
Shift Select Not Working!

### ISSUE THREAD

**Issue by THE-NERD-1** [HJfod/BetterEdit#17]
I'm using the new update of Better edit with MegaHack v7. When I go into the editor everything looks fine until I try to select multiple objects at once with the shift key and mouse. What instead happens is the screen moves around as if I'm not touching the shift key at all.

**Comment by creepers03060** [comment]
The same is happening to me!

**Comment by THE-NERD-1** [comment]
Just add the dll into the geometry dash folder and then add the name of the dll into the absolutedlls file by opening it with notepad. After that it will 100% work.
