### ISSUE TITLE
Editor crashes when returning from playtest

### ISSUE THREAD

**Issue by prplnorangesoda** [HJfod/BetterEdit#178]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/49725587-f722-41a4-8ad0-724d565a4086">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337">
    <img alt="GitHub Octicons: Alert" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337" margin="0px">
  </picture>
  Crash Report
  <br />
</h1>
Report a crash (I.e., when the mod/game closes unexpectedly).
<hr />

## Description
 https://github.com/HJfod/BetterEdit/assets/60671867/e0bbb6de-cabd-45b4-8c5e-ae947517c3c1
 
Entering `Save and Play`, returning, and hitting CTRL+Z consistently crashes my game to desktop

I have not changed any keybinds, this is base BetterEdit
## Crash Log
*Please attach the latest crash log from `…/Geometry Dash/geode/crashlogs`*

[2024-02-13_00-44-43.log](https://github.com/HJfod/BetterEdit/files/14256800/2024-02-13_00-44-43.log)

**Comment by prplnorangesoda** [comment]
now that i look at it, this seems more like a customkeybinds bug than a betteredit bug

**Comment by HJfod** [comment]
likely fixed by #177, reopen if still exists after next BE update!

**Comment by prplnorangesoda** [comment]
seems to have been fixed

**Comment by HJfod** [comment]
Alright, fantastic!
