### ISSUE TITLE
button per row

### ISSUE THREAD

**Issue by Robotop200** [HJfod/BetterEdit#181]
good afternoon to you, can you return the button per row in the editor because I'm not used to it being in a different place, can you return it to the original place 
![Screenshot_2024-02-14-06-39-54-07_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/HJfod/BetterEdit/assets/159965237/090b8877-2c69-463e-9a87-850bc393f9dd)

**Comment by Alphalaneous** [comment]
This is a vanilla feature, just go to the editor settings
![image](https://github.com/HJfod/BetterEdit/assets/38200084/3401ee0c-864c-4f7e-8609-efefd39f0c7f)
