### ISSUE TITLE
Bug layer

### ISSUE THREAD

**Issue by Yoss2003** [HJfod/BetterEdit#185]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/00ac7efc-08a3-4163-b88f-1eabd0307139">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/ec09d442-592b-4b8b-9fd9-58e5ec1af5cb">
    <img alt="GitHub Octicons: Bug" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/ec09d442-592b-4b8b-9fd9-58e5ec1af5cb" margin="0px">
  </picture>
  Bug Report
  <br />
</h1>
Report a bug in the mod &mdash; <i>Use the Crash report form to report crashes, and the Suggestion form to suggest new features!</i>
<hr />

## Bug Description
<i>A clear and concise description of what the bug is - is something not working as expected? Does something look off? Is the mod conflicting with another mod?</i>

Hello! I'm glad that they have corrected the crash of the editor layers, but here I report a bug from the same environment, which is the following (I don't know how to explain it).

## Screenshots
<i>

https://github.com/HJfod/BetterEdit/assets/73543878/6ecb1241-4be0-473d-a014-0ac3e27bf240

</i>

Here you can better see what I mean by layers.

## Platform

> * [ ] Windows
> * [ ] Mac
> * [ ] Android (32-bit)
> * [X] Android (64-bit)
> * [ ] Linux

**Comment by Alphalaneous** [comment]
Can you please start making bug reports properly instead of just ...
Use your words too, not just a video

**Comment by Yoss2003** [comment]
Sorry, I edited it because the text I put in was not displayed, it should
be visible now.

**Comment by DemiSans** [comment]
This is gd bug, not betteredit, but would be cool if betteredit fix that
