### ISSUE TITLE
Edit menu doesn't render correctly on non widescreen aspect ratios

### ISSUE THREAD

**Issue by jbritain** [HJfod/BetterEdit#19]
I am using a 5:4 monitor, and in the edit tab, the buttons are squashed together to the point where some of them are impossible to click, as shown below.
![20220622183611_1](https://user-images.githubusercontent.com/50422789/175101806-7e3b8928-8d1e-4d88-a88c-67e8836e6ee8.jpg)

**Comment by HJfod** [comment]
![image](https://user-images.githubusercontent.com/60038575/175102144-52d3f106-c95a-4e93-bf9b-f35239942038.png)
