### ISSUE TITLE
(mobile) game crashes after inputting text and then tapping OK

### ISSUE THREAD

**Issue by KontrollFreek** [HJfod/BetterEdit#196]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/49725587-f722-41a4-8ad0-724d565a4086">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337">
    <img alt="GitHub Octicons: Alert" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337" margin="0px">
  </picture>
  Crash Report
  <br />
</h1>
Report a crash (I.e., when the mod/game closes unexpectedly).
<hr />

## Description
*What were you doing when the crash happened?*

For example:
 - Were you placing objects?
 - Were you editing colors?
 - Were you playtesting?

I was editing the zoom of a camera guide, typed in 0.97 to the zoom, pressed OK, and the game froze and then crashed.

## Crash Log
*Please attach the latest crash log from `…/Geometry Dash/geode/crashlogs`*

(Geode is only giving me a .dmp instead of a .log, if that works though then I'll send it. I'm on android32, geode 2.0.0-beta.19, betteredit 6.2.1)

**Comment by KontrollFreek** [comment]
nvm apparently this is either an issue with another mod, a geode issue, or a vanilla issue because this happens 70% of the time on android without BE

**Comment by TheSillyDoggo** [comment]
it happens with text bypasses in prism and qolmod so disable the bypasses in the menu
