### ISSUE TITLE
game crashes whenever I attempt to delete a backup of a level

### ISSUE THREAD

**Issue by randyr7** [HJfod/BetterEdit#20]
whenever I attempt to delete a backup of one of my levels it crashes the game (video below showcases it happening)

https://user-images.githubusercontent.com/23731558/179569471-99d0a380-2b74-40cc-9550-8b29ad5f3b7d.mp4

**Comment by randyr7** [comment]
this bug has still not been fixed yet

**Comment by HJfod** [comment]
Am aware, this has been reported multiple times before and I will fix it for BE 5. Haven't bothered doing so yet because I plan on completely rewriting the backup system from scratch (the current one was bodged together in like a day and it sucks)
