### ISSUE TITLE
Non-selectable Area with Scaled UI.

### ISSUE THREAD

**Issue by silvernull** [HJfod/BetterEdit#204]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/00ac7efc-08a3-4163-b88f-1eabd0307139">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/ec09d442-592b-4b8b-9fd9-58e5ec1af5cb">
    <img alt="GitHub Octicons: Bug" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/ec09d442-592b-4b8b-9fd9-58e5ec1af5cb" margin="0px">
  </picture>
Non-selectable Area with Scaled UI.
  <br />
</h1>
Unselectable area in editor.</i>
<hr />

## Bug Description
I am unable to select objects inside of the area I have marked below in red, 
which I assume is due to the scaled UI blocking my interact-able area.

## Screenshots
![image](https://github.com/HJfod/BetterEdit/assets/80038133/0a8a3d6e-c8c4-4a30-9898-4edc433398f1)

## Platform

> * [x] Windows
> * [ ] Mac
> * [ ] Android (32-bit)
> * [ ] Android (64-bit)
> * [ ] Linux

**Comment by TheSillyDoggo** [comment]
Hardcoded checks my beloved ❤️

**Comment by Alphalaneous** [comment]
> Hardcoded checks my beloved ❤️

Does he know :trollface:

**Comment by TheSillyDoggo** [comment]
I did not in fact know because when I said that I didn't even know how to properly reverse engineer
