### ISSUE TITLE
Game crash, when placing ANY object

### ISSUE THREAD

**Issue by InfernuZGD** [HJfod/BetterEdit#206]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/49725587-f722-41a4-8ad0-724d565a4086">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337">
    <img alt="GitHub Octicons: Alert" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337" margin="0px">
  </picture>
  Crash Report
  <br />
</h1>
Report a crash (I.e., when the mod/game closes unexpectedly).
<hr />

## Description
*What were you doing when the crash happened?*

When you place an object, game crashes

## Crash Log
*Please attach the latest crash log from `…/Geometry Dash/geode/crashlogs`*

2024-02-18T21:56:00+0200
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.20
Loader Commit: 453fac9
Bindings Commit: 60e063e
Installed mods: 53
Problems: 0

== Exception Information ==
C++ Exception: class std::length_error("vector<T> too long")
Faulty Mod: <Unknown>

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 13fa72 (RaiseException + 98)
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 19339 (CxxThrowException + 78)
 - C:\WINDOWS\SYSTEM32\MSVCP120.dll + 13a0b (std::_Xlength_error + 46)
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + e1697
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 12f0f3
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 1ab8a1
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 23c055
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + c86c9
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + c8290
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + c7fae
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + d9f27
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + f8b5b (cocos2d::CCTouchDispatcher::touches + 331)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + f8df9 (cocos2d::CCTouchDispatcher::touchesEnded + 25)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + be92c (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 92)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + c7922 (cocos2d::CCEGLView::onGLFWMouseCallBack + 210)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + c794e (cocos2d::CCEGLView::onGLFWMouseCallBack + 254)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + 116cc9 (cocos2d::CCPoint::unrotate + 8073)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + 118819 (cocos2d::CCPoint::unrotate + 15065)
 - G:\steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 10eb4c
 - C:\WINDOWS\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
 - C:\WINDOWS\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
 - C:\WINDOWS\System32\USER32.dll + 372f6 (GetSystemMetricsForDpi + 3142)
 - C:\WINDOWS\System32\USER32.dll + 35aeb (CallWindowProcW + 27)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 4696f (glDebugEntry + 3631)
 - C:\WINDOWS\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
 - C:\WINDOWS\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
 - C:\WINDOWS\System32\USER32.dll + 36471 (DispatchMessageW + 1265)
 - C:\WINDOWS\System32\USER32.dll + 35f90 (DispatchMessageW + 16)
 - G:\steam\gameoverlayrenderer.dll + 83090 (OverlayHookD3D3 + 121824)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
 - G:\steam\steamapps\common\Geometry Dash\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - G:\steam\steamapps\common\Geometry Dash\Geode.dll + 16f4d4 (crashlog::setupPlatformHandlerPost + 3956)
 - G:\steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 67c5e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 67c2e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 0141ede8
EBX: 3fffffff
ECX: 00000003
EDX: 00000000
EBP: 0141ee44
ESP: 0141ede8
EDI: 0141ee94
ESI: 734f5744
EIP: 76a3fa72

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v8.0.0-alpha.10] absolllute.megahack
x | [v1.0.1] alphalaneous.happy_textures
  | [v1.0.1] alphalaneous.hide
x | [v1.0.0] alphalaneous.playercolorselect
x | [v1.0.1] asaki_zuki.same_dual_color
x | [v1.1.0] b1rtek.gddlintegration
x | [v1.0.5] bitz.customprofiles
x | [v1.1.4] capeling.demons_in_garage_2.2
x | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.4] capeling.icon_profile_2.2
x | [v4.0.0] cvolton.betterinfo
x | [v1.1.2] dankmeme.globed2
  | [v2.0.1] devcmb.cleanermenu
x | [v1.0.0] elnexreal.auto_priority
  | [v1.0.3] firee.GoldenBest
x | [v2.4.0] fleym.nongd
x | [v1.2.15] gdutilsdevs.gdutils
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.20] geode.loader
x | [v1.6.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v6.3.0] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
x | [v1.0.1] hjfod.quick-volume-controls
x | [v1.0.1] itzkiba.elegant_rankings
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.1.0] itzkiba.grandpa_demon
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.1.3] mat.circle-tool
x | [v1.0.0] mat.reference-image
x | [v1.0.2] mat.run-info
x | [v1.0.0-beta.5] minemaker0430.gddp_integration
  | [v1.0.4-beta.13] muhammadgames.bettermenu
  | [v1.2.1] n.robtop-jumpscare
x | [v1.1.0] polsk.level_quests
x | [v1.0.0] polsk.pause_settings
  | [v1.0.0] shadyiscool.shadypause
x | [v1.0.1] slammy333.save_button
x | [v1.6.2] spaghettdev.gd-roulette
x | [v2.5.0] techstudent10.discord_rich_presence
x | [v1.0.0] techstudent10.hide_locks
  | [v1.0.0] thesillydoggo.entersearch
  | [v2.1.0] TheSillyDoggo.GradientPages
  | [v1.1.1] TheSillyDoggo.StartposSwitcher
  | [v1.6.0] tpdea.betterpause-Better
x | [v1.0.0] tpdea.sceneswitcher
x | [v1.0.0] tpdea.scroll_any_input
  | [v1.8.1] undefined0.gdtweaks
x | [v1.0.2] weebify.restartbtn
x | [v1.0.0] xanii.freaky_mode
x | [v1.4.6] zilko.xdbot

**Comment by HJfod** [comment]
Fixed in 6.3.1!
