### ISSUE TITLE
Literally impossible to use base grid size while building

### ISSUE THREAD

**Issue by SuperDZ555** [HJfod/BetterEdit#207]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/00ac7efc-08a3-4163-b88f-1eabd0307139">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/ec09d442-592b-4b8b-9fd9-58e5ec1af5cb">
    <img alt="GitHub Octicons: Bug" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/ec09d442-592b-4b8b-9fd9-58e5ec1af5cb" margin="0px">
  </picture>
  Bug Report
  <br />
</h1>
Report a bug in the mod &mdash; <i>Use the Crash report form to report crashes, and the Suggestion form to suggest new features!</i>
<hr />

## Bug Description
<i>A clear and concise description of what the bug is - is something not working as expected? Does something look off? Is the mod conflicting with another mod?</i>

If you try to set the grid size to the regular grid size (30), it physically does not work. It just keeps the same grid size as whatever it was before selecting 30. This goes for using the buttons as well as just typing in the number 30.

## Screenshots
<i>If you have screenshots/videos, please include them!</i>

![image](https://github.com/HJfod/BetterEdit/assets/62621246/736e2907-ec6f-4d7b-bb11-5e207015be3a)
![image](https://github.com/HJfod/BetterEdit/assets/62621246/1686e1db-5e14-4d64-8ea3-c11dfd8feba9)

## Platform

> * [x] Windows
> * [ ] Mac
> * [ ] Android (32-bit)
> * [ ] Android (64-bit)
> * [ ] Linux

**Comment by lookingbehind** [comment]
looks like the custom grid ignores value 30 and follows the previous variable that was set before 30, since it seems to work fine on other values

**Comment by HJfod** [comment]
Fixed in 6.3.1!
