### ISSUE TITLE
Wierd grid size thing

### ISSUE THREAD

**Issue by Baconhub124** [HJfod/BetterEdit#209]
if you change the grid size you cant change it back to the original grid size ):

**Comment by abeljakowoff** [comment]
looks like the custom grid ignores value 30 and follows the previous variable that was set before 30, since it seems to work fine on other values
![image](https://github.com/HJfod/BetterEdit/assets/70239841/792bbea7-4d17-4107-8d92-11c47e6332a3)

**Comment by HJfod** [comment]
Fixed in 6.3.1!
