### ISSUE TITLE
game crashes when i place a block

### ISSUE THREAD

**Issue by Ottopia2910** [HJfod/BetterEdit#210]
## Description
*What were you doing when the crash happened?*
I wanted to built in the editor i just opened it without doing anything and as soon as i placed an object it crashed

For example:
 - Were you placing objects?
 yes

 - Were you editing colors?
no

 - Were you playtesting?
no

## Crash Log

2024-02-18T22:18:37+0100
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.20
Loader Commit: 453fac9
Bindings Commit: 60e063e
Installed mods: 8
Problems: 0

== Exception Information ==
C++ Exception: class std::length_error("vector<T> too long")
Faulty Mod: <Unknown>

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 149392 (RaiseException + 98)
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 18a19 (CxxThrowException + 78)
 - C:\WINDOWS\SYSTEM32\MSVCP120.dll + 13a4f (std::_Xlength_error + 46)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + e1697
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 12f0f3
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 1ab8a1
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 23c055
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + c86c9
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + c8290
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + c7fae
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + d9618
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + f8b71 (cocos2d::CCTouchDispatcher::touches + 353)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + f8e19 (cocos2d::CCTouchDispatcher::touchesMoved + 25)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + beaa0 (cocos2d::CCEGLViewProtocol::handleTouchesMove + 336)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c7a6c (cocos2d::CCEGLView::onGLFWMouseMoveCallBack + 284)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 116bee (cocos2d::CCPoint::unrotate + 7854)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 1188f5 (cocos2d::CCPoint::unrotate + 15285)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 10eb4c
 - C:\WINDOWS\System32\USER32.dll + 32e53 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23c26 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 23597 (CallWindowProcW + 135)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 3be09 (glDebugEntry + 3849)
 - C:\WINDOWS\System32\USER32.dll + 32e53 (Ordinal2713 + 1715)
 - C:\WINDOWS\System32\USER32.dll + 23c26 (CallWindowProcW + 1814)
 - C:\WINDOWS\System32\USER32.dll + 224e5 (DispatchMessageW + 1221)
 - C:\WINDOWS\System32\USER32.dll + 22030 (DispatchMessageW + 16)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 83090 (OverlayHookD3D3 + 121824)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 16f4d4 (crashlog::setupPlatformHandlerPost + 3956)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 005bf370
EBX: 3fffffff
ECX: 00000003
EDX: 00000000
EBP: 005bf3cc
ESP: 005bf370
EDI: 005bf41c
ESI: 786256f4
EIP: 753a9392

== Installed Mods ==
x | [v8.0.0-alpha.10] absolllute.megahack
  | [v1.1.2] dankmeme.globed2
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.20] geode.loader
x | [v1.6.1] geode.node-ids
x | [v6.3.0] hjfod.betteredit
x | [v1.6.0] tpdea.betterpause-Better
x | [v1.4.7] zilko.xdbot
2024-02-18T22:18:37+0100
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.20
Loader Commit: 453fac9
Bindings Commit: 60e063e
Installed mods: 8
Problems: 0

== Exception Information ==
C++ Exception: class std::length_error("vector<T> too long")
Faulty Mod: <Unknown>

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 149392
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 18a19
 - C:\WINDOWS\SYSTEM32\MSVCP120.dll + 13a4f
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + e1697
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 12f0f3
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 1ab8a1
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 23c055
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + c86c9
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + c8290
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + c7fae
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + d9f27
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + f8b5b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + f8df9
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + be92c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c7922
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c794e
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 116cc9
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 116024
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 11834b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + 10eb4c
 - C:\WINDOWS\System32\USER32.dll + 32e53
 - C:\WINDOWS\System32\USER32.dll + 23c26
 - C:\WINDOWS\System32\USER32.dll + 23597
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 3be09
 - C:\WINDOWS\System32\USER32.dll + 32e53
 - C:\WINDOWS\System32\USER32.dll + 23c26
 - C:\WINDOWS\System32\USER32.dll + 236aa
 - C:\WINDOWS\System32\USER32.dll + 2d5bf
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 78ced
 - C:\WINDOWS\System32\USER32.dll + 32e53
 - C:\WINDOWS\System32\USER32.dll + 20698
 - C:\WINDOWS\System32\USER32.dll + 1f5fc
 - C:\WINDOWS\System32\USER32.dll + 1f45d
 - C:\WINDOWS\System32\USER32.dll + 32e53
 - C:\WINDOWS\System32\USER32.dll + 23c26
 - C:\WINDOWS\System32\USER32.dll + 236aa
 - C:\WINDOWS\System32\USER32.dll + 2d5bf
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 78ced
 - C:\WINDOWS\System32\USER32.dll + 28611
 - C:\WINDOWS\System32\USER32.dll + 59d8e
 - C:\WINDOWS\System32\USER32.dll + 7ac60
 - C:\WINDOWS\System32\USER32.dll + 799f6
 - C:\WINDOWS\System32\USER32.dll + 7a4f7
 - C:\WINDOWS\System32\USER32.dll + 7a32e
 - C:\WINDOWS\System32\USER32.dll + 7a045
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 16df9d
 - C:\WINDOWS\System32\KERNELBASE.dll + 212240
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bdbd
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6bcaf

== Register States ==
EAX: 005bd9a0
EBX: 3fffffff
ECX: 00000003
EDX: 00000000
EBP: 005bd9fc
ESP: 005bd9a0
EDI: 005bda4c
ESI: 786256f4
EIP: 753a9392

== Installed Mods ==
x | [v8.0.0-alpha.10] absolllute.megahack
  | [v1.1.2] dankmeme.globed2
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.20] geode.loader
x | [v1.6.1] geode.node-ids
x | [v6.3.0] hjfod.betteredit
x | [v1.6.0] tpdea.betterpause-Better
x | [v1.4.7] zilko.xdbot

**Comment by HJfod** [comment]
Fixed in 6.3.1!
