### ISSUE TITLE
Edit button didn't work

### ISSUE THREAD

**Issue by MoreFroce234** [HJfod/BetterEdit#215]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/49725587-f722-41a4-8ad0-724d565a4086">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337">
    <img alt="GitHub Octicons: Alert" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337" margin="0px">
  </picture>
  Crash Report
  <br />
</h1>
Edit button don't work on Android 32!.
<hr />

## Description
*Edit button don't work for some how?*

… 

## Crash Log
*Please attach the latest crash log from `…/Geometry Dash/geode/crashlogs`*

… 
 
## How to fix?
*Hope you can fix*

**Comment by HJfod** [comment]
Should be fixed in 6.3.2, reopen if the crash persists!
