### ISSUE TITLE
Guaranteed Crash After Few Minutes In Editor

### ISSUE THREAD

**Issue by redcatxus** [HJfod/BetterEdit#235]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/49725587-f722-41a4-8ad0-724d565a4086">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337">
    <img alt="GitHub Octicons: Alert" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/a2cb1371-3075-49eb-90e4-e63081837337" margin="0px">
  </picture>
  Crash Report
  <br />
</h1>
Report a crash (I.e., when the mod/game closes unexpectedly).
<hr />

## Description
Staying in the editor with BE enabled, version 6.3.3, caused the game to crash after a few minutes. Regardless of what you're doing, it will crash if you're in the editor.
Android 11, 64 bit. Geode Beta 20.
I'll leave my discord tag here, because I am not using github that often: @redcatxus

## Crash Log
[Crash 2024-02-22 17.44.41.dmp](https://github.com/HJfod/BetterEdit/files/14374577/Crash.2024-02-22.17.44.41.dmp)

**Comment by ghost** [comment]
Hopefully, this helps you understand what you could write for an issue title - treat it like a news headline! Just summarise the basics of what's going on. 😃

It seems that Android 64 is a bit less stable than other platforms, but I do hope that improves over time.
