### ISSUE TITLE
Double click to Edit Object

### ISSUE THREAD

**Issue by krixic** [HJfod/BetterEdit#241]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/2cec62bc-d984-4557-981f-759a88606d83">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa">
    <img alt="GitHub Octicons: Beaker" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa" margin="0px">
  </picture>
  Suggestion
  <br />
</h1>
Suggest a new feature to be added.
<hr />

### How should it work?
Double clicking an object or trigger should open its 'Edit Object' panel.

### What does it look/sound/act like?
Double clicking an object or trigger
![image](https://github.com/HJfod/BetterEdit/assets/87764007/d6eab8da-7245-49fd-baea-eab092b28fa6)

### What is its purpose?
Should open its 'Edit Object' panel
![image](https://github.com/HJfod/BetterEdit/assets/87764007/959caf90-f4bd-486d-8081-6f25610a4dab)

**Comment by silvernull** [comment]
Additionally, mouse support in customkeybinds could mean having right click for this instead

**Comment by ghost** [comment]
Feels like this could be part of #163

**Comment by HJfod** [comment]
This was in BE v4 and everyone hated it, it's a good idea on paper but you end up spam-clicking a ton in the GD editor to select objects and double-clicking to open up Edit Object just screws that workflow up completely without offering a replacement
