### ISSUE TITLE
Nostalgia

### ISSUE THREAD

**Issue by Getsuga0** [HJfod/BetterEdit#259]
<h1>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/2cec62bc-d984-4557-981f-759a88606d83">
    <source media="(prefers-color-scheme: light)" srcset="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa">
    <img alt="GitHub Octicons: Beaker" width="100" align="left" src="https://github.com/HJfod/BetterEdit/assets/24266948/d9b063f2-24dc-4727-9dc7-c9663f05d9aa" margin="0px">
  </picture>
  Suggestion
  <br />
</h1>
Suggest a new feature to be added.
<hr />

## Feature Description
Where a the old four buttons on the bottom left side of the editor ? I never got the honor of trying it, please add them in the geode version !
### How should it work?
There are the three first ones that you know, build, edit and delete, but also the view button, which allow us to view specific objects of the level. 
### What does it look/sound/act like?
Also, the edit tab has the arrows arranged in a way more intuitive way than they are originally.
### What is its purpose?
To edit better, what a question !

**Comment by thebigcheese192** [comment]
This is going to be added, it's not in BE yet because there are bigger priorities.
