### ISSUE TITLE
mod doesn't work

### ISSUE THREAD

**Issue by o10luckyboy10** [HJfod/BetterEdit#279]
### BetterEdit version

Latest

### Bug description

The mod has all the credits loaded but doesn't have any futures loaded every time I try to use the mod...

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by o10luckyboy10** [comment]
It isn't completed but still. :/

**Comment by HJfod** [comment]
Could you show a screenshot of the mod in the in-game Geode mods browser? And what features are you trying to use?
