### ISSUE TITLE
Lens/Zoom button overlaps with the play button

### ISSUE THREAD

**Issue by DaveConfusion** [HJfod/BetterEdit#287]
### BetterEdit version

Latest

### Bug description

Sometimes when i open the editor, the zoom button is on top of the play button

### Screenshots

![Captura de tela 2024-04-15 164102](https://github.com/HJfod/BetterEdit/assets/92901303/9411d424-1f4a-45b0-abac-b3078f626ac1)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by Alphalaneous** [comment]
Update node IDs
