### ISSUE TITLE
The Geode alpha doesn't do anything

### ISSUE THREAD

**Issue by TheBearodactyl** [HJfod/BetterEdit#29]

**Comment by AnDashik** [comment]
Yes, what should I do to make this file work? Or is it not working at all at the moment??  (i not good know english, i'm belarus)

**Comment by TheBearodactyl** [comment]
> Yes, what should I do to make this file work? Or is it not working at all at the moment?? (i not good know english, i'm belarus)

From what hjfod said in the discord, it might've been a bug with a previous version
