### ISSUE TITLE
bug report ig

### ISSUE THREAD

**Issue by ItzMeIg** [HJfod/BetterEdit#294]
### BetterEdit version

latest

### Bug description

ya know the thing that allows us to enter the layer numbers in editor? well in android while playtesting if accidently clicked in the zone where u are supposed to type in the layer number, it'll just opens the keyboard and thinking im not playtesting

### Screenshots

none

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [X] Android (64-bit)
- [ ] Linux

**Comment by heavyutils** [comment]
This repo needs a roomba so badly

**Comment by HJfod** [comment]
Fixed in latest release
