### ISSUE TITLE
betteredit disables delete button, and turns all blocks deadly

### ISSUE THREAD

**Issue by agooddietconsistsoffood** [HJfod/BetterEdit#295]
### BetterEdit version

v6.3.3

### Bug description

when i use any of the keybinds/buttons do delete an object, it does not delete, instead turning into a deadly version of it.

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
This sounds like a bug in another mod
