### ISSUE TITLE
Error Loading Mods. error how to fix?

### ISSUE THREAD

**Issue by coolneptune** [HJfod/BetterEdit#30]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/114297992/235378268-ac34fde8-a01e-4f58-890c-423734ee558f.png">

**Comment by TheBearodactyl** [comment]
Install the GMD-API mod from the downloads page

**Comment by kurmirika** [comment]
I think im stupid, why cant I find the GMD-API lmao

**Comment by TheBearodactyl** [comment]
> I think im stupid, why cant I find the GMD-API lmao

The latest pre-release in the discord comes with all of the deps, so you should be able to use that instead
