### ISSUE TITLE
Scale lock button dont work

### ISSUE THREAD

**Issue by NonCloud9** [HJfod/BetterEdit#304]
### BetterEdit version

6.3.5

### Bug description

This bugs annoys me because when i want to lock warp to make a perfect scale the button becomes unpressable, i had this issue two updates before.

### Screenshots

https://github.com/HJfod/BetterEdit/assets/85463024/3344e894-1a88-416e-b90a-69181557ea80

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Fixed in latest release
