### ISSUE TITLE
Problem loading betteredit mod/dll

### ISSUE THREAD

**Issue by SerialDesignationK** [HJfod/BetterEdit#31]
i tried to enable the mod in geode, then my PC said entry point not found, then i load back gd, it said error loading mod; Unable to load mod: ERROR_PROC_NOT_FOUND

**Comment by Fleeym** [comment]
You can install the latest alpha version of V5 from the releases tab, which should fix this. You also need GMD API and Custom Keybinds (Geode version, not HJFod). You can get those from the index.
