### ISSUE TITLE
Edit tab displaying build tab sections

### ISSUE THREAD

**Issue by xiyxs** [HJfod/BetterEdit#321]
### BetterEdit version

v6.4.0

### Bug description

When stopping/pausing playtesting, the editor defaults to the edit tab, but the different sections for the build tab still appear at the top.

### Screenshots

![image](https://github.com/HJfod/BetterEdit/assets/158768984/fc33e8a9-24c4-4e7d-94a4-3492f0bf03cb)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by silvernull** [comment]
I can also recreate this 100% of the time.
![image](https://github.com/HJfod/BetterEdit/assets/80038133/f1b03d6b-0baf-417e-acca-6713f5d1aac1)
