### ISSUE TITLE
Exiting before auto-save finished causes "Saving in 0 seconds" to be permanently displayed

### ISSUE THREAD

**Issue by xiyxs** [HJfod/BetterEdit#323]
### BetterEdit version

v6.4.0

### Bug description

If you exit from a level right before it is about to auto-save (I did so because I did not realize auto-save was on and did not want it to save), the text stays on screen until the game is closed. I exited right around 1-0 seconds, maybe exiting before then would not cause this to happen, but I'm unsure.

### Screenshots

![image](https://github.com/HJfod/BetterEdit/assets/158768984/dab47d0a-11b6-41d9-8a94-1baf7104e2db)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by Krzykarek** [comment]
Had the same bug with, saving in one second:
![Zrzut ekranu (517)](https://github.com/HJfod/BetterEdit/assets/107867658/c40fd807-8e01-439d-925d-683a6f4422d9)
