### ISSUE TITLE
Block Type Selection Appearing after Playtesting

### ISSUE THREAD

**Issue by ghost** [HJfod/BetterEdit#324]
### BetterEdit version

BetterEdit v6.4.0

### Bug description

After stopping playtesting, the Block Type Selection appears even in the Edit tab

### Screenshots

Noticed this while working on a new level

After stopping playtesting in the editor, the Block Type Selection appears even in the Edit tab
I don't know any other causes
![image](https://github.com/HJfod/BetterEdit/assets/147777028/5b3aa226-e46c-4151-9cc7-e1f1e94856dd)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by PC4SHH** [comment]
It happens when you pause too
