### ISSUE TITLE
Pls

### ISSUE THREAD

**Issue by TheRealDashYT** [HJfod/BetterEdit#328]
### BetterEdit version

Latest

### Bug description

There was a problem with this mod, I can't load it in

### Screenshots

![Screenshot_20240524-164447](https://github.com/HJfod/BetterEdit/assets/170714599/e1d78ce8-9984-4a1b-840c-5000c10058fc)

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [X] Android (64-bit)
- [ ] Linux

**Comment by im-blad** [comment]
update your mods jeez
