### ISSUE TITLE
Can't Enable BetterEdit v5 in Geode

### ISSUE THREAD

**Issue by RoomTempMilk** [HJfod/BetterEdit#33]
"Unable to load the DLL: ERROR_PROC_NOT_FOUND" keeps popping up everytime i try to enable the mod in geode.

**Comment by SpyderThingy** [comment]
Same

**Comment by Slenderino** [comment]
Same

**Comment by Fulaste** [comment]
Same

**Comment by theyusof** [comment]
Same

**Comment by Fleeym** [comment]
You can install the latest alpha version of V5 from the releases tab, which should fix this. You also need GMD API and Custom Keybinds (Geode version, not HJFod). You can get those from the index.
