### ISSUE TITLE
Does this look right to you?

### ISSUE THREAD

**Issue by Foxiseminger** [HJfod/BetterEdit#337]
### BetterEdit version

v6.4.3

### Bug description

the layers are messed up

### Screenshots

![image_2024-05-25_080236533](https://github.com/HJfod/BetterEdit/assets/158284627/682819b3-1704-4383-9694-20a10af94325)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HappyAlexRomania** [comment]
Same happens when saving builds in the custom objects tab

**Comment by HJfod** [comment]
Fixed in latest release
