### ISSUE TITLE
"Add a Creation" bug

### ISSUE THREAD

**Issue by srandomie** [HJfod/BetterEdit#339]
### BetterEdit version

6.4.0

### Bug description

There is a bug with the "creations" tab in the GD editor. When I try to put something in my creations, everything moves to the right, and i cant see literally anything. It's not a **MAJOR** bug though, since you can just exit the level, but I thought it was worth reporting anyway. (This also happens if i remove one also.)

https://github.com/HJfod/BetterEdit/assets/154935189/620a1334-18d8-4fae-b6ec-473ddab40d34

### Screenshots

![image_2024-05-25_101657373](https://github.com/HJfod/BetterEdit/assets/154935189/1749fc35-0514-49eb-abdb-59790a6246f8)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Fixed in latest release
