### ISSUE TITLE
Not working with BetterSave v2.0.0

### ISSUE THREAD

**Issue by DerpOKat21** [HJfod/BetterEdit#359]
### BetterEdit version

Latest

### Bug description

Despite having BetterSave enabled, BetterEdit complains that it's not higher than v1.2.0

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
BetterEdit does not work in 2.206 at all.

**Comment by HJfod** [comment]
(It will be ported soon)

**Comment by DerpOKat21** [comment]
Thanks for letting me know about that. Good work on Geode, I'm loving it.

**Comment by heavyutils** [comment]
Have you tried to see if it's just the version that's the issue?

**Comment by HJfod** [comment]
@heavyutils BetterEdit does not work in 2.206 yet, no matter what version of BetterSave you have
