### ISSUE TITLE
Error loading mod V5 Geode

### ISSUE THREAD

**Issue by Slenderino** [HJfod/BetterEdit#36]
![image](https://github.com/HJfod/BetterEdit/assets/135389069/8df4d040-6099-462d-b73b-e4aa3621dedd)
This error happensto me and i don´t know why, i know its an alpha but i cannot test it because of this!

**Comment by cursefroge** [comment]
use the one in the better edit discord

**Comment by Fleeym** [comment]
You can install the latest alpha version of V5 from the releases tab, which should fix this. You also need GMD API and Custom Keybinds (Geode version, not HJFod). You can get those from the index.
