### ISSUE TITLE
Ability to input scale value

### ISSUE THREAD

**Issue by DemiSans** [HJfod/BetterEdit#362]
### Feature description

Ability to input scale values with keyboard instead of only using sliders with this stupid 4x limit would be great

### Concept Art

![p3bfvtWA7x](https://github.com/HJfod/BetterEdit/assets/91954696/f11d1c03-91c6-47c3-8ef6-a0965db806a3)
![qzWhQbVXxE](https://github.com/HJfod/BetterEdit/assets/91954696/b724b464-13e9-4e67-aea2-bd8a6c2a4bc3)

**Comment by TdubMorris** [comment]
This was in BE for a while but yeah would be nice to see re-added
