### ISSUE TITLE
Deleted levels re-appear

### ISSUE THREAD

**Issue by sheepdotcom** [HJfod/BetterEdit#365]
### BetterEdit version

v6.5.0

### Bug description

Deleting a level after opening the editor and saving the level and then returning to the main menu, BetterEdit logs that it restores crash data for the level and the level re-appears in your created levels list. Issues occur even when only using BetterEdit and its required dependencies.

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Oh hmm, BetterEdit should remove the crash data when the game is saved succesfully, i.e. doesn't crash. Are you sure you're exiting the game normally?

**Comment by sheepdotcom** [comment]
I dont even have to exit the game for this to happen, I only need to return to main menu for it to reappear.

**Comment by HJfod** [comment]
Oooohhh. I know what the issue is. Will fix
