### ISSUE TITLE
DLL error

### ISSUE THREAD

**Issue by LaderaCookieCo** [HJfod/BetterEdit#38]
![Screenshot 2023-06-15 130702](https://github.com/HJfod/BetterEdit/assets/113142878/113ff949-fb7a-47c9-bb2f-cfae696f5598)

I am on Windows 11

**Comment by Fleeym** [comment]
You can install the latest alpha version of V5 from the releases tab, which should fix this. You also need GMD API and Custom Keybinds (Geode version, not HJFod). You can get those from the index.
