### ISSUE TITLE
Not is possible to use betteredit in the new version 6.6.4 || BetterEdit couldn't load its binary

### ISSUE THREAD

**Issue by Lanalanita** [HJfod/BetterEdit#380]
### BetterEdit version

6.6.4

### Bug description

I can't use betteredit in the new version for a bug called

**BetterEdit couldn't load its binary**

### Screenshots

![Screenshot_20240715-152748_Geode](https://github.com/user-attachments/assets/8f502b7f-bc39-49c5-a5e1-a03c2c7b02e4)

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [X] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Install Custom Keybinds
