### ISSUE TITLE
some Levels force LDM when I enable BetterEdit

### ISSUE THREAD

**Issue by dxnutz3n** [HJfod/BetterEdit#389]
### BetterEdit version

v6.7.0

### Bug description

Nothing related about the editor, but some levels force ldm, whenever I turn it on or off, the result is still the same, so I disabled all mods I have enabled and slowly enabled them one by one, and betteredit was the reason why some levels have ldm prior

### Screenshots

Uploading Screen_Recording_20240728_215028.mp4…

Uploading Screen_Recording_20240728_215057.mp4…

this might not work lol

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [X] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Fixed in latest release
