### ISSUE TITLE
Scale Factor Bug

### ISSUE THREAD

**Issue by Gunnerjooy** [HJfod/BetterEdit#401]
### BetterEdit version

6.7.0

### Bug description

When Scale Factor is less than 1, the object tabs do not go down.

### Screenshots

![20240812170628_1](https://github.com/user-attachments/assets/780bebd3-b243-40e3-9e45-7c5d65e45981)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by Alphalaneous** [comment]
This is actually due to a Pages API bug that was fixed a few days ago, update it to resolve.
