### ISSUE TITLE
Font bug

### ISSUE THREAD

**Issue by Miillilk** [HJfod/BetterEdit#412]
### BetterEdit version

6.7.0

### Bug description

When you go to the settings, and you fant to enter the font, then you have to wait medium life to put the font. I AM NOT CREATED TO HAVE PATIENCE!!!

### Screenshots

I do not have screenshots/videos

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by Miillilk** [comment]
Not fixed bruh

**Comment by HJfod** [comment]
This is an unavoidable side effect of having to load all of the fonts into memory. This can not be properly fixed unless GD becomes a multi-threaded game at its core.

**Comment by Miillilk** [comment]
but i have to wait a medium life to put the font hjgah, but your mod is the best ive ever installen

**Comment by Alphalaneous** [comment]
> This is an unavoidable side effect of having to load all of the fonts into memory. This can not be properly fixed unless GD becomes a multi-threaded game at its core.

Could prolly lazy load it

**Comment by HJfod** [comment]
That would probably make the scrolling layer lag like hell when you tried to scroll it, but ig it's worth a shot

**Comment by Miillilk** [comment]
After 4 months? Nice!
