### ISSUE TITLE
broken buttons

### ISSUE THREAD

**Issue by theme33** [HJfod/BetterEdit#416]
### BetterEdit version

6.7.0

### Bug description

the object select buttons (for example the button you click to build with the default block) are higher than they should be.

### Screenshots

![Screenshot (5)](https://github.com/user-attachments/assets/a5fb38a1-5a07-4e19-b415-ab92a2f497f1)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by Alphalaneous** [comment]
Update EditorTab API
