### ISSUE TITLE
wtf is that

### ISSUE THREAD

**Issue by Slein9** [HJfod/BetterEdit#417]
### BetterEdit version

v6.7.0

### Bug description

if you ask, yes, I turned off all mods except better edit and the mods that are required for it, but when I turned off better edit, this bug (watch screenshot) disappeared, so I'm sure that the problem is not something else, namely better edit

### Screenshots

![Скриншот 01-09-2024 152911](https://github.com/user-attachments/assets/d170f4a3-77fb-4724-9fd0-9de08dcd257d)
![Скриншот 01-09-2024 144730](https://github.com/user-attachments/assets/7ef7d0c3-34ab-41b2-8343-0dace8b0ce8a)

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by Alphalaneous** [comment]
Update EditorTab API
