### ISSUE TITLE
It just doesnt do anything 

### ISSUE THREAD

**Issue by GlutenPlayz** [HJfod/BetterEdit#42]
i put the .geode in the mods folder and it shows up in the modlist but the mod just doenst work (yes it is enabled it says)

unless i missed an installation step idk

**Comment by GlutenPlayz** [comment]
evermind i disabled it and renebaled it to get the same error everyone else is getting

**Comment by Fleeym** [comment]
You can install the latest alpha version of V5 from the releases tab, which should fix this. You also need GMD API and Custom Keybinds (Geode version, not HJFod). You can get those from the index.
