### ISSUE TITLE
BPM has been broken

### ISSUE THREAD

**Issue by Miillilk** [HJfod/BetterEdit#432]
### BetterEdit version

6.7.0

### Bug description

Well, i wanted to doi a Silent Hill layout, and i activated the BPM on the View Tab, and in the song, i put the Start Offset like 1.0, and there was no PBM, Why?!

### Screenshots

Nope, i cannot paste images ;(

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by Miillilk** [comment]
You kidding me??

**Comment by HJfod** [comment]
???? what does this mean
