### ISSUE TITLE
new evrything

### ISSUE THREAD

**Issue by tlon85unit** [HJfod/BetterEdit#436]
### Feature description

new stuff in levels and editor.

### Concept Art

new modes new triggers new evrything

**Comment by tlon85unit** [comment]
can you do that?

**Comment by HJfod** [comment]
While it is theoretically possible to add new gamemodes and blocks, this won't be done in BetterEdit. Any levels using those new gameplay features would require all users playing those levels to also have the mod installed, which would cause a ton of issues
