### ISSUE TITLE
Unintentional LDM

### ISSUE THREAD

**Issue by bigpuna** [HJfod/BetterEdit#439]
### BetterEdit version

Latest

### Bug description

Hey! I just wanna let you know that whenever i turn on BetterEdit, the game plays every level in LDM. plaese help.
I tried without and with a lot of mods to see which was doing it and it came to that its BetterEdit. oh yeah and it doesnt show in the level settings (LDM mode on) 

### Screenshots

https://github.com/user-attachments/assets/1bcbd345-0dcc-4ae3-83c5-87dad740ad30

sorry i had to downscale the video by a crap ton so it fits here. (the video might look a little bad..) oh yeah and the showcase starts with the level 'what'

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Fixed in latest release
