### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by Bituvo** [HJfod/BetterEdit#45]
I get this error message twice when I run GD, then nothing changes in the editor. I'm using the Geode release.
![image](https://github.com/HJfod/BetterEdit/assets/90872694/827d2d72-c347-4bc6-ae0b-cbeab1fd208c)

**Comment by TechStudent10** [comment]
Same here

**Comment by Fleeym** [comment]
You can install the latest alpha version of V5 from the releases tab, which should fix this. You also need GMD API and Custom Keybinds (Geode version, not HJFod). You can get those from the index.
