### ISSUE TITLE
Next free layer doesn't work

### ISSUE THREAD

**Issue by Galaxyte-0** [HJfod/BetterEdit#453]
### BetterEdit version

6.8.0

### Bug description

self-explanatory
disabling BetterEdit fixed it

### Screenshots

https://github.com/user-attachments/assets/c17efadb-fc4c-4bba-8531-760cbe11634b

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [X] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Fixed in latest release
