### ISSUE TITLE
Loosing level

### ISSUE THREAD

**Issue by zodic-ttv** [HJfod/BetterEdit#462]
### BetterEdit version

no idea its the latest one on geode

### Bug description

wwhnever i save my data and turn off my pc the whole level dosent save sometimes leaving the whole level blank. if i copy the level and save and delete EVERYTHING IS GONE

### Screenshots

cant because my level is GONE

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Most likely fixed in latest update, reopen if not
