### ISSUE TITLE
Group tabs are broken

### ISSUE THREAD

**Issue by doopyyyyy** [HJfod/BetterEdit#464]
### BetterEdit version

Latest

### Bug description

When I add a group it multiplies to the middle

### Screenshots

![2024-11-07_22-23](https://github.com/user-attachments/assets/e1955e70-23ed-4208-82b0-7d3d6d2d7637)

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [X] Linux

**Comment by LooferGD** [comment]
I also have the same problem

**Comment by Alphalaneous** [comment]
Update improved group view

**Comment by doopyyyyy** [comment]
its fixed for me now
