### ISSUE TITLE
Custom Repositioning Not Working

### ISSUE THREAD

**Issue by DasshuDev** [HJfod/BetterEdit#471]
### BetterEdit version

v6.9.0-alpha.1 [Pro]

### Bug description

The custom object movement buttons (1/4, 1/8, and Pixel) are not registering at all.

### Screenshots

https://github.com/user-attachments/assets/245a3485-9e48-4589-bc84-51da7d9d15fb

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by DasshuDev** [comment]
Edit: the video was cropped poorly so here you go!

https://github.com/user-attachments/assets/f04735ed-054f-403a-92aa-45a0394f543b

**Comment by HJfod** [comment]
Fixed in latest update
