### ISSUE TITLE
Pls fix the bug

### ISSUE THREAD

**Issue by Namelesslol** [HJfod/BetterEdit#473]
### BetterEdit version

Latest

### Bug description

Bro whenever I click the editing button and then click save and exit or exit it crashes immediately for no reason. Pls fix bruh y'all updated the mod 10 minutes ago and it's already buggy wtf bruh

### Screenshots

https://github.com/user-attachments/assets/01fa93a8-4e73-467b-a6a1-e30229403241

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [X] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
This is probably a QOLMod bug, not related to BetterEdit!
