### ISSUE TITLE
Unable to move objects using 1/4, 1/8, or Pixels buttons.

### ISSUE THREAD

**Issue by Amelintrus** [HJfod/BetterEdit#474]
### BetterEdit version

v6.9.0

### Bug description

I have an object selected, and whenever I press the arrow buttons assigned to 1/4, 1/8, or Pixels, it doesn't move.

### Screenshots

https://github.com/user-attachments/assets/46a1ebb0-544b-42eb-9902-6a23fcc50e42

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Fixed in latest update
