### ISSUE TITLE
New edit menu issue (Android)

### ISSUE THREAD

**Issue by GiMakerGit** [HJfod/BetterEdit#478]
### BetterEdit version

Latest

### Bug description

When trying to turn off new edit menu, and enter the editor - the game crashes

### Screenshots

https://github.com/user-attachments/assets/7ba835a9-aab6-49dc-a493-4369179fecc0

[launcher_logcat.txt](https://github.com/user-attachments/files/17820564/launcher_logcat.txt)

### Platform

- [ ] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [X] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Most likely fixed in latest update, reopen if not
