### ISSUE TITLE
for some reason it says this error message, any idea why?

### ISSUE THREAD

**Issue by DreamboyIsPog** [HJfod/BetterEdit#48]
![image](https://github.com/HJfod/BetterEdit/assets/143079541/858acc64-9d60-413d-b8f1-a8fe73f4f956)

**Comment by catdogmat** [comment]
Same

**Comment by supergunna** [comment]
Yeah, I'm also experiencing this. I think it might be related to the GMD API, but idk

**Comment by catdogmat** [comment]
Its bc you need more dependency's, join the discord server

**Comment by Fleeym** [comment]
You can install the latest alpha version of V5 from the releases tab. You also need GMD API and Custom Keybinds (Geode version, not HJFod). You can get those from the index.
