### ISSUE TITLE
Next free layer buttons in "Edit Group" not working

### ISSUE THREAD

**Issue by GDNatrium** [HJfod/BetterEdit#481]
### BetterEdit version

6.9.1

### Bug description

The "Next Free Layer" buttons in the Edit Group tab don't work as expected. Clicking the "+" button on either Editor L or Editor L2 will change the layer to 0 or 1, depending on if you are currently on layer 0, despite both layer 0 and layer 1 containing objects.

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Fixed in the latest update!
