### ISSUE TITLE
Unable to load DLL

### ISSUE THREAD

**Issue by supergunna** [HJfod/BetterEdit#49]
![1502e31fc966cd2bcc9f7c1ebfcf84c6](https://github.com/HJfod/BetterEdit/assets/79544100/5373f61e-7ceb-406f-b167-bc008a89cb10)
I've seen other people with this issue, and I really just want to know how to fix it. Is it a problem with GMD API? I don't know.

**Comment by rV4nxZ** [comment]
I have the same issue_

**Comment by Noruas23** [comment]
You have to put the minhook dll from the better edit zip into gds directory

**Comment by Eliteik** [comment]
what is gds directory?

> You have to put the minhook dll from the better edit zip into gds directory

**Comment by Noruas23** [comment]
GeometryDash's drectory

**Comment by Noruas23** [comment]
Whete your GeometryDash.exe is

**Comment by josephgamin69** [comment]
> You have to put the minhook dll from the better edit zip into gds directory

hi, i put the dll into the folder where my exe is, and it still has the same issue. is there anything else i could be doing wrong?

**Comment by Fleeym** [comment]
Hey, we're talking about BetterEdit v5 here, which is only for the Geode mod loader. You can find the latest alpha release here on github. Alongside that, you have to install GMD API and Custom Keybinds (the Geode version, not HJFod)
