### ISSUE TITLE
hotkeys don't work

### ISSUE THREAD

**Issue by Kirilyha** [HJfod/BetterEdit#490]
### BetterEdit version

latest in geode

### Bug description

on the regular version you can move an item using w a s d and unfold it using q r when with this mod it just doesn’t work
I'll be honest, it's really annoying

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
I believe this has been fixed in the latest release, reopen if not!
