### ISSUE TITLE
Editor build tab is fixed to just objects used in 1.0 when editing level

### ISSUE THREAD

**Issue by Mocha100** [HJfod/BetterEdit#498]
### BetterEdit version

Latest

### Bug description

When I'm editing a level, the build tab only has the 1.0 objects, sorry i don't have a video
nevermind the "I GOT BANNED" thing

### Platform

- [X] Windows
- [ ] Mac
- [ ] Android (32-bit)
- [ ] Android (64-bit)
- [ ] Linux

**Comment by HJfod** [comment]
Sounds like you have some mod installed that restricts to 1.0 objects? This can not possibly be a BetterEdit bug though

**Comment by Mocha100** [comment]
Nevermind, it isn't betteredit

**Comment by Mocha100** [comment]
it was "Retro Edit"
