### ISSUE TITLE
Geode alpha won't work.

### ISSUE THREAD

**Issue by MCwarden25** [HJfod/BetterEdit#50]
![image](https://github.com/HJfod/BetterEdit/assets/112827991/ae5f9c7b-79c4-4bf1-bed8-7a62da7e52d1)
![image](https://github.com/HJfod/BetterEdit/assets/112827991/a342c6a6-21cc-4a35-ada2-2c6e80829070)

**Comment by Someone68** [comment]
yeah same

**Comment by TheBearodactyl** [comment]
> ![image](https://user-images.githubusercontent.com/112827991/266128927-ae5f9c7b-79c4-4bf1-bed8-7a62da7e52d1.png) ![image](https://user-images.githubusercontent.com/112827991/266128994-a342c6a6-21cc-4a35-ada2-2c6e80829070.png)

don't use the release from the release button, use the one from the GitHub actions tab

**Comment by CattoDev** [comment]
Use the one from the discord releases tab lmao
