### ISSUE TITLE
Game Crashing While Minimizing & When I Die In Custom Level

### ISSUE THREAD

**Issue by MikaKC** [HJfod/BetterEdit#7]
Hi, I've just downloaded this mod using ModLdr and it seems that when the game is minimized & when dying while playtesting custom made level (not in the editor in the level select page), the game crashes.

I do not know if it's an error on my side, or if the mod is broken, but disabling the mods in my mod menu seems to fix the issues.

Thanks again for reading this :)

**Comment by not-nef** [comment]
Hey there! First of all you should definitely join HJfods Discord Server, since there will more likely be people that help you. Second of all, ModLdr is outdated. You should use quickldr instead. The Download is also in the discord server: https://discord.gg/K9Kuh3hzTC
