### ISSUE TITLE
playtesting is VERY broken

### ISSUE THREAD

**Issue by Adrianoowo** [HJfod/BetterEdit#74]
it seems to have some bugged collisions with objects.

https://github.com/HJfod/BetterEdit/assets/129294493/e2cc898a-c93c-4d6c-8085-8637408a2a99

not only that, but it ignores every level start settings i put in.

https://github.com/HJfod/BetterEdit/assets/129294493/b598ac56-a7bf-4675-a6cc-48603ebb542f

now, it might just be some installed mods conflicting with one another, but BE is the only editor mod i have on Geode, and every MH "Creator" setting is turned off. 
in case this is useful, i am running this on a Steam Deck. it shouldn't really make much difference though, as the game functions _relatively_ normally.

**Comment by Alphalaneous** [comment]
This is a Megahack bug, not a betteredit bug

**Comment by netflexy** [comment]
It is megahack bug, but only in geode

**Comment by netflexy** [comment]
without geode mh works fine

**Comment by Adrianoowo** [comment]
makes sense. thanks for the replies.

**Comment by Adrianoowo** [comment]
makes sense. thanks for the replies
