### ISSUE TITLE
Editor group bug (Geode)

### ISSUE THREAD

**Issue by Prokiller-dev** [HJfod/BetterEdit#76]
I have a level with 200 groups, and whenever betteredit is in gd, whenever I want to use a new group and click on next free, it always puts me on group 31 or 32, even tho it has been used before. This only happened to me on the geode version, which I know is experimental, I just wanted to say incase you didnt know about this bug.

**Comment by Prokiller-dev** [comment]
Also, is there a quickfix for this? I cant build my level like this, as it would take twice as much time and energy to do it.

**Comment by VideoBotYT** [comment]
i can't even use betteredit with geode it instantly crashes

**Comment by VideoBotYT** [comment]
> I can't even install BetterEdit

wel weird thing now it works for me to install better edit
