### ISSUE TITLE
Game Crashes when Playing Game

### ISSUE THREAD

**Issue by uhmily** [HJfod/BetterEdit#8]
The game is crashing on this line:

https://github.com/HJfod/BetterEdit/blob/24ad0a9f9f10f1a95957f96a379a7aad517fe1dc/tools/CustomKeybinds/KeybindManager.cpp#L1140

While I'm playing a level, as it is somehow executing that line while not in the editor, and of course it crashes the game since LevelEditorLayer::get() returns null.

**Comment by DePianoman** [comment]
These are the mods I have loaded, forgot to post that last time
![image](https://user-images.githubusercontent.com/23054839/141713192-9d99dbbb-f965-4946-8397-c36b211170db.png)

**Comment by not-nef** [comment]
Downgrading to 4.0.2 fixes the issue afaik, if not, fod will definitely help you.

**Comment by HJfod** [comment]
Hm, that is very odd. The game shouldn't be executing any keybinds that have the type `KBEditor` at that point. The BetterGD version of keybind customization rewamps the categories system, so this should be fixed when that is released.

**Comment by HJfod** [comment]
Should be fixed in v4.0.5.
