### ISSUE TITLE
Start preferences ignored while playtesting in editor

### ISSUE THREAD

**Issue by gameboxng** [HJfod/BetterEdit#83]
I've recently installed BetterEdit and have been looking through all my old levels with it. One problem I have is that it does not take into account the starting preferences you can set within the editor, instead always defaulting to 1x speed cube.

I'm on Alpha 10 by the way.

**Comment by Fleeym** [comment]
Hey, this is an issue related to Smart Start Pos, you can disable it from the mod settings. Most start position stuff is not gonna be worked on before 2.2, because we'll need to figure out how to do them with the channel system and arrow trigger

**Comment by gameboxng** [comment]
> Hey, this is an issue related to Smart Start Pos, you can disable it from the mod settings. Most start position stuff is not gonna be worked on before 2.2, because we'll need to figure out how to do them with the channel system and arrow trigger

I have it disabled, and it still does not work. I am talking about the starting conditions you set for the level, not StartPos, if that helps.

**Comment by Fleeym** [comment]
Oh. I'll look into that then
