### ISSUE TITLE
Game crashes specifically on second launch of editor

### ISSUE THREAD

**Issue by carameltaffy2** [HJfod/BetterEdit#86]
Yea, the game will crash if i open the editor a second time, and specifically a second time. Super weird

OS:
MacOS

Mods:
- Arbitrary Align
- Better Loading
- Better Menu
- BetterEdit
- BetterInfo
- Custom Keybinds
- Circle Tool
- Crystal Client
- Drawing Utilities
- Editor API
- Editor Hitbox Fix
- Fullscreen Fix
- GDUtils
- GDShare
- Globed
- GMD API
- Icon Profile
- NONGD
- Practice Music
- Run Info
- Song Randomizer
- Texture Loader
- Volume Scroll Wheel

Thats a lot of mods, sorry lmao

Crashlog.
[2023-11-26_15-30-11.log](https://github.com/HJfod/BetterEdit/files/13468287/2023-11-26_15-30-11.log)

**Comment by carameltaffy2** [comment]
It was circle tool smh

**Comment by nnadire** [comment]
why the fuck do you use bettermenu and arbitrary align and practice music and run info and drawing utilities

**Comment by CribonGarge** [comment]
better menu is just nice, Haven't tried arbitrary align yet, practice music is QoL, and i am a vector artist, so being able to import svgs is a very nice feature.

**Comment by carameltaffy2** [comment]
> why the fuck do you use bettermenu and arbitrary align and practice music and run info and drawing utilities

better menu is just nice, Haven't tried arbitrary align yet, practice music is QoL, and i am a vector artist, so being able to import svgs is a very nice feature.
